spring:
  application:
    name: Config-Dev
    tag: new

eureka:
  instance:
    prefer-ip-address: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
