spring:
  application:
    name: Config-Prod
    Tag: latest-new-2

eureka:
  instance:
    prefer-ip-address: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
